### ISSUE TITLE
White screen of death

### ISSUE THREAD

**Issue by JoshBox** [wedi/limit-login-countries#2]
Hi

I've installed limit-login-countries and I'm getting the following issue:

Fatal error: error traversing database - perhaps it is corrupt? in /homepages/23/d509459907/htdocs/Home/wp-content/plugins/limit-login-countries/vendor/geoip/geoip.inc on line 613

Any ideas?

Thanks

j

**Comment by wedi** [comment]
Hi Josh,
could you please check your php memory limit? This error usually happens when there is not enough memory to read the GeoIP database.
Also download a fresh copy of the GeoIP database and replace the one you are using just to make sure the file is not currupt.
Dirk

**Comment by wedi** [comment]
Hi Josh,
I have updated the plugin. It would be great if you could test the [current version](http://downloads.wordpress.org/plugin/limit-login-countries.0.6.3.zip) in your environment.
Thank you.
